export default {
  files: [
    'assets/czs-angle-down-l.svg',
    'assets/czs-angle-up-l.svg',
    'assets/czs-github-logo.svg',
    'assets/czs-menu-l.svg',
    'assets/czs-moon.svg',
    'assets/czs-moon-l.svg',
    'assets/czs-pen.svg',
    'assets/czs-sun.svg',
    'assets/czs-sun-l.svg',
    'assets/index.css',
    'assets/prism.css',
    'assets/prism_tomorrow.css',
    'assets/reset.css',
    'assets/variables.css',
    '_footer.tsx',
    '_head.tsx',
    '_header.tsx',
    '_layout.tsx',
    '_loading.tsx',
    '_main.tsx',
    '_popover.tsx',
    '_sidebar.tsx',
    '_tools.tsx',
    '_utils.tsx',
    'favicon.ico'
  ]
};
